### ISSUE TITLE
Determine how to make Cloudflare Tunnel + TLS play nicely with wildcard hostnames

### ISSUE THREAD

**Issue by ankushg** [ankushg/home-cluster#312]
### Desired Behavior
I want to annotate an ingress with the following and have it automatically accessible via a Cloudflare Tunnel

```yaml
# Hostname
coredns.io/hostname: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"

## public access via tunnel
external-dns.alpha.kubernetes.io/target: "homelab-tunnel.${SECRET_DOMAIN}"
external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
external-dns/is-public: "true"
```

### Current Behavior
In addition to the above, I **also** need to explicitly specify hostnames in cloudflared config's ingress rules.

https://github.com/ankushg/home-cluster/blob/main/cluster/apps/networking/traefik/cloudflared-config/cloudflared-config.yaml#L18

If I try setting `originServerName: "${SECRET_DOMAIN}"`, I get a traefik error complaining that:
```
{"level":"debug","msg":"http: TLS handshake error from 10.42.1.1:3869: strict SNI enabled - No certificate found for domain: \”${SECRET_DOMAIN}\", closing connection","time":"2022-07-01T15:13:16Z"}
```

From what I can tell, I have configured the following:
- both production and staging `ClusterIssuer` include `${SECRET_DOMAIN}` in `dnsZones`: https://github.com/ankushg/home-cluster/blob/main/cluster/core/cluster-issuers/letsencrypt-production.yaml
- `default` TLSStore with a certificate defined : https://github.com/ankushg/home-cluster/blob/main/cluster/apps/networking/traefik/tls-store/default.yaml
- `default` TLSOptions: https://github.com/ankushg/home-cluster/blob/main/cluster/apps/networking/traefik/default-tls-options/default-tls-option.yaml
